// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwzB6S62SQrnxpkEpwOaAGhuMFSRaaD04',
    appId: '1:740275780229:web:d0d55040695158cafb87ec',
    messagingSenderId: '740275780229',
    projectId: 'test-upload-image-59582',
    authDomain: 'test-upload-image-59582.firebaseapp.com',
    storageBucket: 'test-upload-image-59582.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYSW5DUeUgODRylfUkSCEKdxNOcEgTT8',
    appId: '1:740275780229:android:016782dbc3b544f6fb87ec',
    messagingSenderId: '740275780229',
    projectId: 'test-upload-image-59582',
    storageBucket: 'test-upload-image-59582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZNQmXtMOwkq4xnEm0Ku-HZQ1zPt0iFLU',
    appId: '1:740275780229:ios:56124a0f2d5dfb52fb87ec',
    messagingSenderId: '740275780229',
    projectId: 'test-upload-image-59582',
    storageBucket: 'test-upload-image-59582.appspot.com',
    iosBundleId: 'com.example.imageUploadTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZNQmXtMOwkq4xnEm0Ku-HZQ1zPt0iFLU',
    appId: '1:740275780229:ios:bb77390672732545fb87ec',
    messagingSenderId: '740275780229',
    projectId: 'test-upload-image-59582',
    storageBucket: 'test-upload-image-59582.appspot.com',
    iosBundleId: 'com.example.imageUploadTest.RunnerTests',
  );
}
